### ISSUE TITLE
Received errors about undefined reference to min

### ISSUE THREAD

**Issue by paulelong** [pkourany/I2CDEV_MPU6050#11]
Using PIO with VSCode and the ESP8266 chip, I received a few errors while trying to compile.  On line 300, it errored that min was undefined.  Changing that to std::min resolved the problem.  Next it complained that there was not a version of min that accepted a uint8_t and int, and I fixed that by casting the first param as an int.  My solution is below, which now compiles. 

`            for (uint8_t k = 0; k < length; k += std::min((int)length, BUFFER_LENGTH)) {`

**Comment by pkourany** [comment]
@paulelong, this repo is a fork of[ this library](https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050), adapted for Particle devices.  You may want to post your issue in that repo.
