### ISSUE TITLE
invalid preprocessing directive 

### ISSUE THREAD

**Issue by CandidCypher** [pkourany/I2CDEV_MPU6050#8]
MPU6050/I2Cdev.h:78:2: error: invalid preprocessing directive #warnings
 #warnings ARDUINO !!!

**Comment by pkourany** [comment]
@CandidCypher, this is caused by the latest Particle preprocessor.  The warning indicates the compiler thinks it is compiling for an Arduino instead of a Particle device.  I will be reviewing this library to see if it should be updated to Libraries v2.0 and fix the issue as well.

**Comment by pkourany** [comment]
PR merged!
